In [1]:
import equinox as eqx
import gym
import jax
import jax.numpy as jnp
import jax.random as jrandom
import numpy as np
import optax
import sys
import timeit
import wandb

from argparse import Namespace
from functools import partial
from jax import grad, jit, vmap
from typing import Sequence, Tuple

from jax_learning.agents.rl_agents import RLAgent
from jax_learning.buffers.ram_buffers import NextStateNumPyBuffer
from jax_learning.buffers.utils import batch_flatten, to_jnp
from jax_learning.constants import DISCRETE, CONTINUOUS
from jax_learning.rl_utils import interact, evaluate

from jax_learning.models import Policy, ActionValue, MLP, StochasticPolicy

In [2]:
wandb.init(project="test_jax_rl", group="reacher-reinforce_test")
wandb.define_metric("episodic_return", summary="max")

/Users/chanb/work/personal_research/jax_learning/.venv/lib/python3.10/site-packages/notebook/utils.py:280: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  return LooseVersion(v) >= LooseVersion(check)
wandb: Currently logged in as: chan. Use `wandb login --relogin` to force relogin
/Users/chanb/work/personal_research/jax_learning/.venv/lib/python3.10/site-packages/wandb/sdk/lib/ipython.py:47: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML  # type: ignore


In [3]:
cfg_dict = {
    # Environment setup
    "env": "Reacher-v2",
    "seed": 0,
    "render": False,
    "clip_action": True,
    "max_action": 1.,
    "min_action": -1.,
    
    # Experiment progress
    "load_step": 0,
    "log_interval": 5000,
    
    # Learning hyperparameters
    "gamma": 0.99,
    "max_timesteps": 1000000,
    "update_frequency": 128,
    "lr": 1e-2,
    "max_grad_norm": 10.,
    
    # Model architecture
    "hidden_dim": 256,
    "num_hidden": 2,
    
    # Evaluation
    "eval_cfg": {
        "max_episodes": 100,
        "seed": 1,
        "render": True,
        "clip_action": True,
        "max_action": 1.,
        "min_action": -1.,
    }
}
cfg = Namespace(**cfg_dict)
eval_cfg = Namespace(**cfg.eval_cfg)
wandb.config = cfg_dict

In [4]:
np.random.seed(cfg.seed)

In [5]:
env = gym.make(cfg.env)

/Users/chanb/work/personal_research/jax_learning/.venv/lib/python3.10/site-packages/gym/envs/registration.py:564: UserWarning: WARN: The environment Reacher-v2 is out of date. You should consider upgrading to version `v4`.
  logger.warn(
/Users/chanb/work/personal_research/jax_learning/.venv/lib/python3.10/site-packages/gym/envs/mujoco/mujoco_env.py:46: UserWarning: WARN: This version of the mujoco environments depends on the mujoco-py bindings, which are no longer maintained and may stop working. Please upgrade to the v4 versions of the environments (which depend on the mujoco python bindings instead), unless you are trying to precisely replicate previous works).
  logger.warn(
<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
objc[29917]: Class GLFWWindowDelegate is implemented in both /usr/local/Cellar/glfw/3.3.7/lib/libglfw.3.3.dylib (0x1163be7b0) and /Users/chanb/.mujoco/mu

In [6]:
cfg.obs_dim = env.observation_space.shape
cfg.act_dim = env.action_space.shape
cfg.action_space = CONTINUOUS

In [7]:
cfg.h_state_dim = (1,)
cfg.rew_dim = (1,)

In [8]:
cfg

Namespace(env='Reacher-v2', seed=0, render=False, clip_action=True, max_action=1.0, min_action=-1.0, load_step=0, log_interval=5000, gamma=0.99, max_timesteps=1000000, update_frequency=128, lr=0.01, max_grad_norm=10.0, hidden_dim=256, num_hidden=2, eval_cfg={'max_episodes': 100, 'seed': 1, 'render': True, 'clip_action': True, 'max_action': 1.0, 'min_action': -1.0}, obs_dim=(11,), act_dim=(2,), action_space='continuous', h_state_dim=(1,), rew_dim=(1,))

In [9]:
cfg.buffer_rng = np.random.RandomState(cfg.seed)
cfg.env_rng = np.random.RandomState(cfg.seed)
cfg.agent_key, cfg.model_key = jrandom.split(jrandom.PRNGKey(cfg.seed), num=2)
eval_cfg.env_rng = np.random.RandomState(eval_cfg.seed)

In [15]:
from jax_learning.distributions import Distribution, Normal


class MLPGaussianPolicy(StochasticPolicy):
    obs_dim: int
    act_dim: int
    eps: float
    policy: eqx.Module

    def __init__(self,
                 obs_dim: Sequence[int],
                 act_dim: Sequence[int],
                 hidden_dim: int,
                 num_hidden: int,
                 key: jrandom.PRNGKey,
                 eps: float=1e-7):
        self.obs_dim = int(np.product(obs_dim))
        self.act_dim = int(np.product(act_dim))
        self.eps = eps
        self.policy = MLP(self.obs_dim, self.act_dim * 2, hidden_dim, num_hidden, key)

    def deterministic_action(self,
                             obs: np.ndarray,
                             h_state: np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        act_mean, _ = jnp.split(self.policy(obs), 2, axis=-1)
        return act_mean, h_state
    
    def random_action(self,
                      obs: np.ndarray,
                      h_state: np.ndarray,
                      key: jrandom.PRNGKey) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        dist = self.dist(obs, h_state)
        act = dist.sample(key)
        return act, h_state
    
    def act_lprob(self,
                  obs: np.ndarray,
                  h_state: np.ndarray,
                  key: jrandom.PRNGKey) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        dist = self.dist(obs, h_state)
        act = dist.sample(key)
        lprob = dist.lprob(act)
        return act, lprob, h_state
    
    def dist(self,
             obs: np.ndarray,
             h_state: np.ndarray) -> Distribution:
        act_mean, act_raw_std = jnp.split(self.policy(obs), 2, axis=-1)
        act_std = jax.nn.softplus(act_raw_std) + self.eps
        return Normal(act_mean, act_std)


In [16]:
from jax_learning.buffers import ReplayBuffer
from jax_learning.learners import Learner

POLICY = "policy"
LOSS = "loss"
MEAN_LOSS = "mean_loss"
MAX_RETURN = "max_return"
MIN_RETURN = "min_return"
class REINFORCE(Learner):
    def __init__(self,
                 model: eqx.Module,
                 opt: optax.GradientTransformation,
                 buffer: ReplayBuffer,
                 cfg: Namespace):
        super().__init__(model, opt, buffer, cfg)
        
        self._step = cfg.load_step
        self._update_frequency = cfg.update_frequency
        self._sample_idxes = np.arange(cfg.update_frequency)
        self._gamma = cfg.gamma
        
        def get_lprob(dist, act):
            return jnp.sum(dist.lprob(act), keepdims=True)
        
        def score_function(lprob, ret):
            return lprob * ret
        
        @eqx.filter_grad(has_aux=True)
        def reinforce_loss(model: eqx.Module,
                           obss: np.ndarray,
                           h_states: np.ndarray,
                           acts: np.ndarray,
                           rets: np.ndarray) -> Tuple[np.ndarray, dict]:
            dists = jax.vmap(model.dist)(obss, h_states)
            lprobs = jax.vmap(get_lprob)(dists, acts)
            
            scores = jax.vmap(score_function)(lprobs, rets)
            loss = -jnp.mean(scores)
            return loss, {
                LOSS: loss,
                MAX_RETURN: jnp.max(rets),
                MIN_RETURN: jnp.min(rets),
                "dists": dists,
                "lprobs": lprobs,
                "scores": scores
            }
        
        def step(model: eqx.Module,
                 opt: optax.GradientTransformation,
                 opt_state: optax.OptState,
                 obss: np.ndarray,
                 h_states: np.ndarray,
                 acts: np.ndarray,
                 rets: np.ndarray) -> Tuple[eqx.Module, optax.OptState, jax.tree_util.PyTreeDef, dict]:
            grads, learn_info = reinforce_loss(model,
                                               obss,
                                               h_states,
                                               acts,
                                               rets)

            updates, opt_state = opt.update(grads, opt_state)
            model = eqx.apply_updates(model, updates)
            return model, opt_state, grads, learn_info
        self.step = eqx.filter_jit(step)
        
    def compute_returns(self, rews, dones):
        rets = np.zeros(rews.shape[0] + 1)
        for step in reversed(range(len(rews))):
            rets[step] = rets[step + 1] * self._gamma * (1 - dones[step]) + rews[step]
        return rets[:-1]

    def learn(self,
              next_obs: np.ndarray,
              next_h_state: np.ndarray,
              learn_info: dict):
        self._step += 1
        
        if self._step % self._update_frequency != 0:
            return

        obss, h_states, acts, rews, dones, _, _, _ = self.buffer.sample(batch_size=self._update_frequency,
                                                                        idxes=self._sample_idxes)

        rets = self.compute_returns(rews, dones)
        (obss, h_states, acts, rets) = to_jnp(*batch_flatten(obss,
                                                             h_states,
                                                             acts,
                                                             rets))
        model, opt_state, grads, curr_learn_info = self.step(model=self.model[POLICY],
                                                             opt=self.opt[POLICY],
                                                             opt_state=self.opt_state[POLICY],
                                                             obss=obss,
                                                             h_states=h_states,
                                                             acts=acts,
                                                             rets=rets)

        print(curr_learn_info["lprobs"])
        print(curr_learn_info["dists"].mean, curr_learn_info["dists"].std)
        print(curr_learn_info["scores"])
        print(model.policy.weights[-1].weight)
        print(model.policy.biases[-1])
        print(grads.policy.weights[-1].weight)
        print(grads.policy.biases[-1])
        print("=" * 100)
        assert self._step <= 6000

        self._model[POLICY] = model
        self._opt_state[POLICY] = opt_state

        learn_info[MEAN_LOSS] = curr_learn_info[LOSS].item()
        self.buffer.clear()

In [17]:
buffer = NextStateNumPyBuffer(
    buffer_size=cfg.update_frequency,
    obs_dim=cfg.obs_dim,
    h_state_dim=cfg.h_state_dim,
    act_dim=(1,) if cfg.action_space == DISCRETE else cfg.act_dim,
    rew_dim=cfg.rew_dim,
    rng=cfg.buffer_rng,
)

model = {
    POLICY: MLPGaussianPolicy(obs_dim=cfg.obs_dim,
                              act_dim=cfg.act_dim,
                              hidden_dim=cfg.hidden_dim,
                              num_hidden=cfg.num_hidden,
                              key=cfg.model_key,
                              eps=1e-4)
}

opt = {
    POLICY: optax.chain(optax.clip_by_global_norm(cfg.max_grad_norm),  # Clip by the gradient by the global norm
                        optax.scale_by_adam(),  # Use the updates from adam
                        optax.scale(-1.0)) # Gradient descent
}


learner = REINFORCE(model=model,
                    opt=opt,
                    buffer=buffer,
                    cfg=cfg)

agent = RLAgent(model=model,
                model_key=POLICY,
                buffer=buffer,
                learner=learner,
                key=cfg.agent_key)

In [18]:
%wandb

In [19]:
interact(env, agent, cfg)

[[-1.0910294]
 [-1.7010369]
 [-4.416682 ]
 [-1.6514733]
 [-1.1796126]
 [-6.382763 ]
 [-1.2415278]
 [-1.6817632]
 [-1.3658898]
 [-1.5978715]
 [-1.5620415]
 [-2.6773694]
 [-1.3686035]
 [-1.2207258]
 [-2.032523 ]
 [-2.9138284]
 [-1.3762307]
 [-1.4547474]
 [-1.5658554]
 [-2.752273 ]
 [-2.3574128]
 [-1.7982812]
 [-1.1981305]
 [-2.5892181]
 [-2.5536783]
 [-2.8135762]
 [-2.036829 ]
 [-1.3046618]
 [-1.57158  ]
 [-2.049324 ]
 [-1.2603221]
 [-3.6423445]
 [-2.437175 ]
 [-1.5148313]
 [-1.4176459]
 [-3.1579876]
 [-1.7641993]
 [-1.7174438]
 [-1.3036623]
 [-1.8136446]
 [-2.1237602]
 [-2.0036387]
 [-1.9474576]
 [-1.4955722]
 [-1.876626 ]
 [-2.9864473]
 [-4.0532703]
 [-1.609286 ]
 [-1.2316461]
 [-2.1705184]
 [-2.0403814]
 [-2.039529 ]
 [-1.254119 ]
 [-1.7612857]
 [-1.7910677]
 [-4.123208 ]
 [-1.3277681]
 [-1.137247 ]
 [-1.3364236]
 [-0.8767302]
 [-1.3515855]
 [-1.2727724]
 [-1.3137594]
 [-0.9980736]
 [-1.9036696]
 [-3.2515106]
 [-0.5569221]
 [-4.9689007]
 [-1.658597 ]
 [-3.0550785]
 [-3.4758193]
 [-2.4

[[-26.778578]
 [-28.354488]
 [-27.74334 ]
 [-25.981659]
 [-25.90392 ]
 [-25.79721 ]
 [-24.913763]
 [-25.575325]
 [-24.201351]
 [-26.12061 ]
 [-26.079157]
 [-25.22062 ]
 [-25.868538]
 [-22.0043  ]
 [-23.115192]
 [-22.313526]
 [-20.921158]
 [-21.680967]
 [-24.572428]
 [-23.688047]
 [-24.298029]
 [-25.37779 ]
 [-21.491516]
 [-22.649565]
 [-24.69767 ]
 [-24.702682]
 [-25.094784]
 [-26.557156]
 [-27.536736]
 [-26.115292]
 [-26.279808]
 [-26.68435 ]
 [-26.59713 ]
 [-26.047405]
 [-27.137245]
 [-26.27406 ]
 [-26.297022]
 [-27.539482]
 [-26.480133]
 [-30.635113]
 [-30.495567]
 [-27.687462]
 [-27.550558]
 [-30.184578]
 [-27.149826]
 [-27.13456 ]
 [-28.071903]
 [-27.61156 ]
 [-28.205647]
 [-27.528145]
 [-27.50887 ]
 [-28.305876]
 [-28.246029]
 [-28.622803]
 [-29.884695]
 [-27.838507]
 [-28.169771]
 [-28.267536]
 [-28.458324]
 [-28.46266 ]
 [-28.915833]
 [-27.773945]
 [-30.744709]
 [-28.172451]
 [-28.086082]
 [-27.96851 ]
 [-27.963764]
 [-28.576046]
 [-28.479427]
 [-28.113194]
 [-30.168663]
 [-28.

[[-1.9532041e+05]
 [-7.8125800e+05]
 [-9.9318686e+00]
 [-3.1250095e+06]
 [-7.8125756e+05]
 [-6.6412859e+00]
 [-5.7116365e+00]
 [-4.8836637e+04]
 [-1.9531909e+05]
 [-6.6609850e+00]
 [-1.9531861e+05]
 [-6.6419115e+00]
 [-4.8834438e+04]
 [-6.3269157e+00]
 [-7.8125694e+05]
 [-6.5891771e+00]
 [-7.8125819e+05]
 [-1.9531930e+05]
 [-7.0131559e+00]
 [-7.8125794e+05]
 [-7.8125688e+05]
 [-7.8125700e+05]
 [-7.2064695e+00]
 [-3.1250075e+06]
 [-3.1250075e+06]
 [-7.8125988e+05]
 [-7.0699520e+00]
 [-7.8879976e+00]
 [-3.1250080e+06]
 [-8.4732656e+00]
 [-7.1649637e+00]
 [-7.8125725e+05]
 [-7.7152605e+00]
 [-7.8125944e+05]
 [-3.1250082e+06]
 [-8.3010492e+00]
 [-3.1250078e+06]
 [-3.1250075e+06]
 [-7.8125738e+05]
 [-3.1250082e+06]
 [-3.1250078e+06]
 [-7.5033789e+00]
 [-7.8125769e+05]
 [-3.1250078e+06]
 [-2.7339830e+00]
 [-5.9153585e+00]
 [-1.2212923e+04]
 [-7.4648161e+00]
 [-6.3795948e+00]
 [-1.9531914e+05]
 [-6.8121166e+00]
 [-6.7009468e+00]
 [-1.9531970e+05]
 [-1.9532028e+05]
 [-2.0281235e+01]
 [-3.05600

[[-1.00189314e+01]
 [-7.97774601e+00]
 [-1.00297804e+01]
 [-1.25000100e+07]
 [-8.31366062e+00]
 [-1.25000110e+07]
 [-8.34286022e+00]
 [-1.25000100e+07]
 [-9.43476009e+00]
 [-1.25000100e+07]
 [-5.00000120e+07]
 [-1.25000100e+07]
 [-1.25000100e+07]
 [-8.37762928e+00]
 [-8.43308353e+00]
 [-8.53144741e+00]
 [-1.94801758e+02]
 [-7.66459412e+02]
 [-7.81256625e+05]
 [-7.81257375e+05]
 [-3.12500775e+06]
 [-1.25000090e+07]
 [-8.82810688e+00]
 [-8.11950207e+00]
 [-9.95440769e+00]
 [-1.25000100e+07]
 [-3.12500850e+06]
 [-7.70593643e+00]
 [-3.12500825e+06]
 [-7.94602108e+00]
 [-8.64083767e+00]
 [-5.00000120e+07]
 [-1.25000100e+07]
 [-1.25000120e+07]
 [-5.00000120e+07]
 [-8.32802486e+00]
 [-8.42088604e+00]
 [-8.75892735e+00]
 [-9.17591953e+00]
 [-8.32697201e+00]
 [-1.02129107e+01]
 [-9.41854572e+00]
 [-1.25000100e+07]
 [-8.40147114e+00]
 [-1.25000100e+07]
 [-1.25000100e+07]
 [-1.25000100e+07]
 [-5.00000120e+07]
 [-8.45213604e+00]
 [-8.58664799e+00]
 [-1.12500016e+08]
 [-1.25000100e+07]
 [-1.2500014

[[-7.0557919e+00]
 [-1.2500009e+07]
 [-1.2500011e+07]
 [-7.8859301e+00]
 [-8.0991812e+00]
 [-8.1090841e+00]
 [-1.2500010e+07]
 [-1.2500010e+07]
 [-9.0867491e+00]
 [-1.2500010e+07]
 [-5.0000012e+07]
 [-2.0000002e+08]
 [-8.9735746e+00]
 [-8.8900900e+00]
 [-2.0000002e+08]
 [-5.0000012e+07]
 [-8.8706255e+00]
 [-8.9257383e+00]
 [-9.2189360e+00]
 [-5.0000012e+07]
 [-9.0589342e+00]
 [-5.0000012e+07]
 [-1.0525529e+01]
 [-9.1165247e+00]
 [-2.0000002e+08]
 [-9.6362391e+00]
 [-9.2525225e+00]
 [-2.0000002e+08]
 [-1.0206313e+01]
 [-5.0000012e+07]
 [-9.4426889e+00]
 [-9.3053446e+00]
 [-9.3557291e+00]
 [-2.0000002e+08]
 [-2.0000002e+08]
 [-2.0000002e+08]
 [-2.0000002e+08]
 [-2.0000002e+08]
 [-3.0653009e+00]
 [-7.8125831e+05]
 [-1.2500009e+07]
 [-1.2500010e+07]
 [-1.2500010e+07]
 [-9.7652082e+00]
 [-5.0000012e+07]
 [-8.6796751e+00]
 [-5.0000012e+07]
 [-5.0000016e+07]
 [-8.1534929e+00]
 [-8.7563772e+00]
 [-1.1250002e+08]
 [-5.0000012e+07]
 [-8.7284040e+00]
 [-5.0000012e+07]
 [-5.0000016e+07]
 [-1.00857

[[-8.00000064e+08]
 [-8.00000064e+08]
 [-9.57718945e+00]
 [-2.00000016e+08]
 [-2.00000016e+08]
 [-2.00000016e+08]
 [-1.22356100e+01]
 [-9.97448444e+00]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-1.93526962e+02]
 [-1.25000100e+07]
 [-1.00165548e+01]
 [-8.26504803e+00]
 [-5.00000120e+07]
 [-5.00000120e+07]
 [-5.00000120e+07]
 [-9.41200542e+00]
 [-9.36404514e+00]
 [-1.21145201e+01]
 [-5.00000120e+07]
 [-9.57265568e+00]
 [-9.28645039e+00]
 [-5.00000120e+07]
 [-2.00000016e+08]
 [-5.00000120e+07]
 [-5.00000120e+07]
 [-5.00000120e+07]
 [-9.56231976e+00]
 [-9.61432743e+00]
 [-2.00000016e+08]
 [-9.47473049e+00]
 [-2.00000016e+08]
 [-2.00000016e+08]
 [-1.80000013e+09]
 [-2.00000016e+08]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-2.00000016e+08]
 [-8.00000064e+08]
 [-9.79679394e+00]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-9.93662357e+00]
 [-8.00000064e+08]
 [-1.07553911e+01]
 [-2.00000016e+08]
 [-2.00000016e+08]
 [-9.99155521e+00]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-1.00453482e+01]
 [-8.0000006

[[-8.0000006e+08]
 [-9.9780397e+00]
 [-1.0525760e+01]
 [-8.0000006e+08]
 [-8.0000006e+08]
 [-1.1102641e+01]
 [-8.0000006e+08]
 [-1.0659034e+01]
 [-1.0470410e+01]
 [-1.1348298e+01]
 [-1.0182988e+01]
 [-8.0000006e+08]
 [-8.0000006e+08]
 [-1.0796119e+01]
 [-1.0387977e+01]
 [-1.0284272e+01]
 [-8.0000006e+08]
 [-8.0000006e+08]
 [-3.2000003e+09]
 [-3.2000003e+09]
 [-8.0000006e+08]
 [-1.0419068e+01]
 [-1.0469638e+01]
 [-3.2000003e+09]
 [-1.0526650e+01]
 [-1.1161771e+01]
 [-3.2000003e+09]
 [-3.2000003e+09]
 [-1.2800001e+10]
 [-3.2000003e+09]
 [-3.2000003e+09]
 [-1.0639609e+01]
 [-4.7987413e+00]
 [-4.1598911e+00]
 [-7.6770878e+00]
 [-1.2500009e+07]
 [-8.9813795e+00]
 [-9.0367785e+00]
 [-2.0000002e+08]
 [-9.1951628e+00]
 [-9.6905432e+00]
 [-2.0000002e+08]
 [-2.0000002e+08]
 [-9.0995359e+00]
 [-9.3390226e+00]
 [-8.0000006e+08]
 [-2.0000002e+08]
 [-9.7492037e+00]
 [-9.8339987e+00]
 [-8.0000006e+08]
 [-1.0452140e+01]
 [-1.0133729e+01]
 [-2.0000002e+08]
 [-1.0350640e+01]
 [-2.0000002e+08]
 [-9.76234

[[-1.08085260e+01]
 [-2.88000020e+10]
 [-1.08925676e+01]
 [-3.20000026e+09]
 [-1.22115684e+04]
 [-3.05639673e+03]
 [-7.08600044e+00]
 [-1.05436506e+01]
 [-8.57574177e+00]
 [-7.32806587e+00]
 [-5.00000120e+07]
 [-9.43531513e+00]
 [-8.70707989e+00]
 [-7.72540379e+00]
 [-1.75781900e+06]
 [-1.25000100e+07]
 [-3.12500725e+06]
 [-1.25000100e+07]
 [-6.12501812e+00]
 [-7.95798206e+00]
 [-8.67426777e+00]
 [-9.03806782e+00]
 [-2.00000016e+08]
 [-2.00000016e+08]
 [-9.71958256e+00]
 [-8.00000064e+08]
 [-1.11026449e+01]
 [-1.14191675e+01]
 [-1.00052328e+01]
 [-1.00594873e+01]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-8.00000064e+08]
 [-1.09270964e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.06661520e+01]
 [-3.20000026e+09]
 [-1.07018175e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.17749319e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.10821638e+01]
 [-1.13256559e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-3.2000002

[[-1.03181925e+01]
 [-1.13114939e+01]
 [-3.20000026e+09]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-1.07323599e+01]
 [-1.04710207e+01]
 [-1.04924536e+01]
 [-1.11428766e+01]
 [-1.14732542e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.11550951e+01]
 [-1.06037397e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.07112360e+01]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.09893789e+01]
 [-1.07525396e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.05580469e+03]
 [-8.04222202e+00]
 [-5.00000120e+07]
 [-1.25000100e+07]
 [-5.00000120e+07]
 [-2.00000016e+08]
 [-8.00000064e+08]
 [-1.09157057e+01]
 [-3.20000026e+09]
 [-1.02347059e+01]
 [-8.00000064e+08]
 [-1.02816801e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.09342833e+01]
 [-3.20000026e+09]
 [-8.00000064e+08]
 [-1.03922567e+01]
 [-1.04758787e+01]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.15554571e+01]
 [-3.20000026e+09]
 [-1.09704771e+01]
 [-1.28000010e+10]
 [-1.2800001

[[-7.03125750e+06]
 [-5.00000120e+07]
 [-9.07267857e+00]
 [-2.00000016e+08]
 [-9.81536388e+00]
 [-9.95223904e+00]
 [-8.00000064e+08]
 [-7.20000051e+09]
 [-3.20000026e+09]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-1.03048639e+01]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.24033327e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.18288221e+01]
 [-1.12754869e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.16696634e+01]
 [-1.14176397e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.12853537e+01]
 [-1.09646940e+01]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.10272150e+01]
 [-1.14658518e+01]
 [-1.11115198e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-1.22111895e+04]
 [-4.88336250e+04]
 [-6.73792362e+00]
 [-1.12500016e+08]
 [-3.1250080

[[-3.20000026e+09]
 [-1.16184950e+01]
 [-1.16195173e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.14625597e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.10724249e+01]
 [-1.14828920e+01]
 [-1.13074389e+01]
 [-1.11716261e+01]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.12247381e+01]
 [-1.28000010e+10]
 [-1.23428030e+01]
 [-1.28000010e+10]
 [-1.19065924e+01]
 [-1.28000010e+10]
 [-3.78135014e+00]
 [-1.12500016e+08]
 [-5.00000120e+07]
 [-2.00000016e+08]
 [-1.14603472e+01]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.18110151e+01]
 [-1.07473269e+01]
 [-1.28000010e+10]
 [-1.21147242e+01]
 [-1.17368650e+01]
 [-1.08773088e+01]
 [-1.14711332e+01]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.09351702e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.11288271e+01]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.13599024e+01]
 [-1.21283941e+01]
 [-1.28000010e+10]
 [-1.1360005

[[-2.00000016e+08]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-8.00000064e+08]
 [-1.07086802e+01]
 [-1.11335859e+01]
 [-1.04782934e+01]
 [-1.06291647e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.10583754e+01]
 [-1.15138502e+01]
 [-3.20000026e+09]
 [-1.09254866e+01]
 [-1.09789152e+01]
 [-1.20356283e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.10694113e+01]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.13023062e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.13818693e+01]
 [-1.32138700e+01]
 [-1.28000010e+10]
 [-1.12734480e+01]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-1.26476851e+01]
 [-1.16242476e+01]
 [-1.28000010e+10]
 [-1.16169844e+01]
 [-1.24893198e+01]
 [-1.28000010e+10]
 [-1.14116182e+01]
 [-1.22108164e+04]
 [-1.25000100e+07]
 [-1.07772932e+01]
 [-5.00000120e+07]
 [-7.17206860e+00]
 [-8.55030346e+00]
 [-2.00000016e+08]
 [-5.00000160e+07]
 [-8.24570751e+00]
 [-9.03470325e+00]
 [-2.0000001

[[-1.1800475e+01]
 [-1.2800001e+10]
 [-1.1691892e+01]
 [-1.3416104e+01]
 [-1.2800001e+10]
 [-1.2800001e+10]
 [-1.2800001e+10]
 [-1.2800001e+10]
 [-1.4628333e+01]
 [-1.1821050e+01]
 [-1.2800001e+10]
 [-5.1200004e+10]
 [-1.1520001e+11]
 [-1.2800001e+10]
 [-3.6591339e+00]
 [-5.0000012e+07]
 [-2.0000002e+08]
 [-2.0000002e+08]
 [-9.3254786e+00]
 [-2.0000002e+08]
 [-2.0000002e+08]
 [-9.7789774e+00]
 [-1.3716414e+01]
 [-8.0000006e+08]
 [-1.0869504e+01]
 [-3.2000003e+09]
 [-1.1129649e+01]
 [-3.2000003e+09]
 [-3.2000003e+09]
 [-3.2000003e+09]
 [-1.0957179e+01]
 [-1.1140805e+01]
 [-1.1488412e+01]
 [-3.2000003e+09]
 [-1.2800001e+10]
 [-1.2800001e+10]
 [-1.2800001e+10]
 [-1.2800001e+10]
 [-5.1200004e+10]
 [-1.1485621e+01]
 [-5.1200004e+10]
 [-1.2800001e+10]
 [-1.2397803e+01]
 [-5.1200004e+10]
 [-1.2800001e+10]
 [-1.1638747e+01]
 [-1.1659808e+01]
 [-5.1200004e+10]
 [-1.1750957e+01]
 [-1.2381610e+01]
 [-5.1200004e+10]
 [-1.1789493e+01]
 [-1.2800001e+10]
 [-1.1674050e+01]
 [-5.1200004e+10]
 [-5.12000

[[-1.0340194e+01]
 [-3.2000003e+09]
 [-1.0460523e+01]
 [-3.2000003e+09]
 [-1.1100579e+01]
 [-1.2044175e+01]
 [-3.2000003e+09]
 [-1.0841882e+01]
 [-3.2000003e+09]
 [-2.8800002e+10]
 [-3.2000003e+09]
 [-1.2800001e+10]
 [-3.2000003e+09]
 [-1.0989945e+01]
 [-1.2800001e+10]
 [-1.2800001e+10]
 [-3.2000003e+09]
 [-1.1064059e+01]
 [-1.1118453e+01]
 [-1.1383798e+01]
 [-1.1316709e+01]
 [-1.2800001e+10]
 [-1.1418000e+01]
 [-1.2215802e+01]
 [-1.2800001e+10]
 [-1.2800001e+10]
 [-1.1465779e+01]
 [-1.2800001e+10]
 [-1.1216102e+01]
 [-1.2800001e+10]
 [-1.1157136e+01]
 [-1.2573142e+01]
 [-1.2800001e+10]
 [-5.1200004e+10]
 [-1.1265105e+01]
 [-1.1370288e+01]
 [-3.5509233e+00]
 [-8.6827116e+00]
 [-4.8834867e+04]
 [-5.0000012e+07]
 [-1.0121596e+01]
 [-8.0000006e+08]
 [-1.0299556e+01]
 [-8.0000006e+08]
 [-1.0760560e+01]
 [-1.0552220e+01]
 [-3.2000003e+09]
 [-1.2800001e+10]
 [-3.2000003e+09]
 [-1.0998372e+01]
 [-3.2000003e+09]
 [-3.2000003e+09]
 [-3.2000003e+09]
 [-1.1931928e+01]
 [-3.2000003e+09]
 [-1.28000

[[-3.20000026e+09]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.14317389e+01]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-3.05587402e+03]
 [-8.75157452e+00]
 [-2.00000016e+08]
 [-2.00000016e+08]
 [-1.03058004e+01]
 [-2.00000016e+08]
 [-5.00000120e+07]
 [-9.49380779e+00]
 [-9.95689869e+00]
 [-8.00000064e+08]
 [-1.03616285e+01]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-1.06306505e+01]
 [-1.07809858e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.06826582e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.11344900e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.22912741e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.14245653e+01]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.13619261e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-1.22415514e+01]
 [-1.14968462e+01]
 [-1.27424002e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.31283407e+01]
 [-1.20815763e+01]
 [-1.19796553e+01]
 [-1.2800001

[[-2.00000016e+08]
 [-8.00000064e+08]
 [-9.83133984e+00]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.07126551e+01]
 [-1.22185297e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.11504698e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.14481134e+01]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.13316927e+01]
 [-1.15125799e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.27880487e+01]
 [-6.87044922e+03]
 [-8.62991810e+00]
 [-9.58859539e+00]
 [-8.00000064e+08]
 [-9.18855190e+00]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-1.02808867e+01]
 [-1.06641359e+01]
 [-8.00000064e+08]
 [-1.08537512e+01]
 [-1.28000010e+10]
 [-1.09214277e+01]
 [-1.11314096e+01]
 [-8.00000064e+08]
 [-1.17601976e+01]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-1.07810678e+01]
 [-3.20000026e+09]
 [-1.08993158e+01]
 [-1.0990279

[[-1.28000010e+10]
 [-1.14018965e+01]
 [-3.05567041e+03]
 [-8.39463139e+00]
 [-1.00811357e+01]
 [-2.00000016e+08]
 [-2.00000016e+08]
 [-8.00000064e+08]
 [-1.11577749e+01]
 [-1.09802599e+01]
 [-8.00000064e+08]
 [-1.00597467e+01]
 [-1.08459501e+01]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.08298044e+01]
 [-1.09632978e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.18728857e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-2.88000020e+10]
 [-1.25727873e+01]
 [-1.12597322e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.14300451e+01]
 [-1.28000010e+10]
 [-1.15301733e+01]
 [-1.15410624e+01]
 [-1.16568975e+01]
 [-1.21737089e+01]
 [-1.17095633e+01]
 [-1.19218149e+01]
 [-1.17630606e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.18583937e+01]
 [-1.23737154e+01]
 [-1.18628702e+01]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-4.4866933

[[-1.08162966e+01]
 [-1.10533953e+01]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-1.00990820e+01]
 [-1.05449286e+01]
 [-3.20000026e+09]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-1.10221434e+01]
 [-3.20000026e+09]
 [-1.18569155e+01]
 [-1.11252527e+01]
 [-3.20000026e+09]
 [-1.26988134e+01]
 [-1.13243895e+01]
 [-1.28000010e+10]
 [-1.17300100e+01]
 [-1.28000010e+10]
 [-1.14603987e+01]
 [-3.05935913e+03]
 [-8.11870861e+00]
 [-9.06972408e+00]
 [-9.58149815e+00]
 [-1.04883566e+01]
 [-1.01861410e+01]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.19232740e+01]
 [-1.01854753e+01]
 [-3.20000026e+09]
 [-1.40921392e+01]
 [-9.80922985e+00]
 [-8.00000064e+08]
 [-1.03652067e+01]
 [-1.04507113e+01]
 [-1.13395967e+01]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-1.11385469e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-8.00000064e+08]
 [-1.06039305e+01]
 [-3.2000002

[[-9.97975445e+00]
 [-2.00000016e+08]
 [-1.03136625e+01]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-8.00000064e+08]
 [-1.12985106e+01]
 [-8.00000064e+08]
 [-1.03089342e+01]
 [-3.20000026e+09]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-1.05167398e+01]
 [-3.20000026e+09]
 [-1.09510164e+01]
 [-1.09582605e+01]
 [-1.09930964e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.14030771e+01]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.16743746e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.16695490e+01]
 [-1.16845732e+01]
 [-1.18932791e+01]
 [-1.19774618e+01]
 [-1.19633551e+01]
 [-1.28000010e+10]
 [-1.18474226e+01]
 [-3.05627881e+03]
 [-7.81256750e+05]
 [-7.81257125e+05]
 [-8.36160946e+00]
 [-9.85017300e+00]
 [-8.51294041e+00]
 [-5.0000012

[[-3.20000026e+09]
 [-1.17682543e+01]
 [-1.11652765e+01]
 [-1.23238153e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.22451582e+01]
 [-1.12055120e+01]
 [-1.14925032e+01]
 [-1.13224115e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.17504148e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-4.52032566e+00]
 [-8.22793484e+00]
 [-5.00000120e+07]
 [-5.00000160e+07]
 [-9.80922985e+00]
 [-9.76928043e+00]
 [-9.03369236e+00]
 [-2.00000016e+08]
 [-2.00000016e+08]
 [-1.00675211e+01]
 [-2.00000016e+08]
 [-1.01916075e+01]
 [-1.16556559e+01]
 [-2.00000016e+08]
 [-8.00000064e+08]
 [-1.05343027e+01]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-1.15648890e+01]
 [-1.06109686e+01]
 [-1.07034311e+01]
 [-8.00000064e+08]
 [-1.09397268e+01]
 [-1.10313101e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.19738035e+01]
 [-3.20000026e+09]
 [-1.16931448e+01]
 [-1.28000010e+10]
 [-1.2265507

[[-5.00000160e+07]
 [-9.82282352e+00]
 [-1.03460684e+01]
 [-8.00000064e+08]
 [-1.03895998e+01]
 [-8.00000064e+08]
 [-1.09818335e+01]
 [-3.20000026e+09]
 [-1.10974989e+01]
 [-1.08020277e+01]
 [-1.09205675e+01]
 [-8.00000064e+08]
 [-1.09103785e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-3.20000026e+09]
 [-1.15609274e+01]
 [-1.11445570e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.15529261e+01]
 [-1.19063540e+01]
 [-3.20000026e+09]
 [-1.13361731e+01]
 [-1.28000010e+10]
 [-1.31619101e+01]
 [-1.14207468e+01]
 [-3.20000026e+09]
 [-1.15080080e+01]
 [-1.15584917e+01]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.17817335e+01]
 [-1.17829790e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.18875284e+01]
 [-1.28000010e+10]
 [-4.20132637e+00]
 [-8.45873165e+00]
 [-1.05382528e+01]
 [-8.75521564e+00]
 [-5.00000120e+07]
 [-2.00000016e+08]
 [-2.00000016e+08]
 [-8.00000064e+08]
 [-1.12748423e+01]
 [-1.04655008e+01]
 [-1.15390959e+01]
 [-1.15447779e+01]
 [-1.1186881

[[-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.20435495e+01]
 [-1.33156595e+01]
 [-1.12776594e+01]
 [-1.11548433e+01]
 [-1.15808039e+01]
 [-1.15619364e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-4.40524769e+00]
 [-8.50785160e+00]
 [-2.00000016e+08]
 [-1.07743597e+01]
 [-2.00000016e+08]
 [-2.00000016e+08]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-1.10720816e+01]
 [-1.35197248e+01]
 [-1.16076975e+01]
 [-1.28000010e+10]
 [-1.09221640e+01]
 [-1.10245237e+01]
 [-1.11039934e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.11353693e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.22250624e+01]
 [-3.20000026e+09]
 [-1.21386461e+01]
 [-1.28000010e+10]
 [-1.14223738e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.14407969e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.15120134e+01]
 [-1.2800001

[[-1.07035627e+01]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-8.00000064e+08]
 [-1.14742975e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.16111650e+01]
 [-3.20000026e+09]
 [-1.18330965e+01]
 [-1.28000010e+10]
 [-1.12765570e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.12851458e+01]
 [-3.20000026e+09]
 [-1.13716173e+01]
 [-2.88000020e+10]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.20645227e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.16538992e+01]
 [-1.15766516e+01]
 [-1.16874037e+01]
 [-1.35834818e+01]
 [-1.17546492e+01]
 [-3.20000026e+09]
 [-2.88000020e+10]
 [-3.20000026e+09]
 [-2.88000020e+10]
 [-5.10159969e+00]
 [-1.95319797e+05]
 [-7.31442642e+00]
 [-1.25000100e+07]
 [-5.00000120e+07]
 [-8.00000064e+08]
 [-5.00000160e+07]
 [-5.00000160e+07]
 [-2.00000016e+08]
 [-2.00000016e+08]
 [-5.00000120e+07]
 [-9.81501102e+00]
 [-2.00000016e+08]
 [-1.26674604e+01]
 [-1.35462046e+01]
 [-8.00000064e+08]
 [-1.22931948e+01]
 [-1.01250696e+01]
 [-8.0000006

[[-1.23763742e+01]
 [-1.19393377e+01]
 [-1.31278887e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-4.82814789e+00]
 [-7.81257000e+05]
 [-7.81257688e+05]
 [-8.73964214e+00]
 [-1.00400553e+01]
 [-9.20291233e+00]
 [-5.00000120e+07]
 [-8.00000064e+08]
 [-2.00000016e+08]
 [-1.04601374e+01]
 [-1.07291708e+01]
 [-1.06839476e+01]
 [-1.07515612e+01]
 [-8.00000064e+08]
 [-1.21634226e+01]
 [-8.00000064e+08]
 [-1.17696409e+01]
 [-1.16689692e+01]
 [-1.08111811e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.35031691e+01]
 [-1.19168501e+01]
 [-1.19841070e+01]
 [-1.11790438e+01]
 [-1.17779150e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.15543718e+01]
 [-1.20374899e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.14455576e+01]
 [-1.28000010e+10]
 [-1.16961317e+01]
 [-3.20000026e+09]
 [-1.17421274e+01]
 [-1.16701441e+01]
 [-1.16996355e+01]
 [-1.28000010e+10]
 [-3.2000002

[[-3.20000026e+09]
 [-3.20000026e+09]
 [-1.48402243e+01]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.11697721e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.15758028e+01]
 [-1.29687567e+01]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.14647970e+01]
 [-3.20000026e+09]
 [-1.37417459e+01]
 [-1.16337080e+01]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-3.05653125e+03]
 [-1.25000110e+07]
 [-7.03125750e+06]
 [-9.33223057e+00]
 [-2.00000016e+08]
 [-2.00000016e+08]
 [-1.08150072e+01]
 [-1.04468412e+01]
 [-1.07500658e+01]
 [-1.11216097e+01]
 [-7.20000051e+09]
 [-3.20000026e+09]
 [-1.04965754e+01]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-1.12528429e+01]
 [-1.09151926e+01]
 [-3.20000026e+09]
 [-1.23292208e+01]
 [-1.13488913e+01]
 [-1.15451021e+01]
 [-3.20000026e+09]
 [-1.09397535e+01]
 [-3.2000002

[[-9.41174984e+00]
 [-6.92838860e+00]
 [-3.12500825e+06]
 [-9.14519978e+00]
 [-1.01934080e+01]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-1.03251944e+01]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-8.00000064e+08]
 [-1.12318907e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.12999849e+01]
 [-3.20000026e+09]
 [-1.15833769e+01]
 [-1.11851282e+01]
 [-1.25835924e+01]
 [-1.15087118e+01]
 [-1.28000010e+10]
 [-1.33380003e+01]
 [-1.15030222e+01]
 [-3.20000026e+09]
 [-1.15291643e+01]
 [-1.14880915e+01]
 [-1.21490679e+01]
 [-1.15635843e+01]
 [-1.16039324e+01]
 [-1.26438131e+01]
 [-1.20691824e+01]
 [-1.28000010e+10]
 [-1.24727736e+01]
 [-1.28000010e+10]
 [-1.17873812e+01]
 [-1.55128946e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.18718939e+01]
 [-1.30088053e+01]
 [-1.28000010e+10]
 [-1.35050497e+01]
 [-1.15200008e+11]
 [-1.21441641e+01]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.24564066e+01]
 [-3.05788184e+03]
 [-1.25000100e+07]
 [-2.0000001

[[-3.20000026e+09]
 [-3.20000026e+09]
 [-1.12622881e+01]
 [-3.20000026e+09]
 [-1.16697607e+01]
 [-3.20000026e+09]
 [-1.10403414e+01]
 [-1.15874834e+01]
 [-1.28000010e+10]
 [-1.15551825e+01]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.43947821e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.15632029e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.16710100e+01]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-5.08783817e+00]
 [-5.00000120e+07]
 [-9.55623722e+00]
 [-1.05681486e+01]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.18291044e+01]
 [-1.27635412e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.20624285e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.15699625e+01]
 [-5.12000041e+10]
 [-1.40408640e+01]
 [-1.28000010e+10]
 [-1.14063025e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.4297787

[[-9.13347149e+00]
 [-2.00000016e+08]
 [-1.49918184e+01]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-1.02036600e+01]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-1.23074389e+01]
 [-1.01951990e+01]
 [-8.00000064e+08]
 [-2.00000016e+08]
 [-1.06629572e+01]
 [-1.09329634e+01]
 [-3.20000026e+09]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-1.06474905e+01]
 [-1.11870604e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.07790575e+01]
 [-3.20000026e+09]
 [-1.11299562e+01]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-1.03884935e+01]
 [-3.20000026e+09]
 [-1.04006414e+01]
 [-8.00000064e+08]
 [-1.07937613e+01]
 [-1.09855070e+01]
 [-1.11392622e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.10817461e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.22123633e+04]
 [-6.95489979e+00]
 [-8.04938984e+00]
 [-2.00000016e+08]
 [-2.00000016e+08]
 [-8.00000064e+08]
 [-1.48436499e+01]
 [-1.03797617e+01]
 [-3.2000002

[[-1.29822397e+01]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.14248571e+01]
 [-1.15180788e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.28703909e+01]
 [-1.28000010e+10]
 [-1.17763815e+01]
 [-1.28000010e+10]
 [-1.15200008e+11]
 [-1.31302881e+01]
 [-1.40816889e+01]
 [-1.16572866e+01]
 [-1.18453112e+01]
 [-4.88342070e+04]
 [-3.12500750e+06]
 [-8.09940434e+00]
 [-9.35391712e+00]
 [-2.00000016e+08]
 [-9.70727444e+00]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-8.00000064e+08]
 [-1.15948763e+01]
 [-9.94197941e+00]
 [-1.01058779e+01]
 [-3.20000026e+09]
 [-8.00000064e+08]
 [-1.13442583e+01]
 [-1.09917974e+01]
 [-1.12835550e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.13296347e+01]
 [-1.37544184e+01]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.33068876e+01]
 [-1.22308264e+01]
 [-1.16437311e+01]
 [-1.11527662e+01]
 [-3.20000026e+09]
 [-1.15312548e+01]
 [-1.20340109e+01]
 [-1.14942942e+01]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-1.15849390e+01]
 [-1.28000010e+10]
 [-1.2800001

[[-1.01740313e+01]
 [-8.00000064e+08]
 [-1.09846678e+01]
 [-8.00000064e+08]
 [-1.09291716e+01]
 [-1.28000010e+10]
 [-1.13257895e+01]
 [-1.12711630e+01]
 [-2.88000020e+10]
 [-1.28000010e+10]
 [-1.16223040e+01]
 [-5.12000041e+10]
 [-1.16303034e+01]
 [-1.37952852e+01]
 [-1.28000010e+10]
 [-1.24053946e+01]
 [-1.19655008e+01]
 [-1.28000010e+10]
 [-1.23073149e+01]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.25247145e+01]
 [-1.28000010e+10]
 [-1.18308687e+01]
 [-1.26168776e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.15200008e+11]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.19603853e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.20475988e+01]
 [-1.21573973e+01]
 [-1.22122773e+04]
 [-2.00000016e+08]
 [-9.95453548e+00]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-1.09045668e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.14209318e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.1454869

[[-1.3635720e+01]
 [-1.1579278e+01]
 [-1.2085496e+01]
 [-1.1388085e+01]
 [-1.1469235e+01]
 [-5.1200004e+10]
 [-1.1820741e+01]
 [-5.1200004e+10]
 [-1.1744153e+01]
 [-1.2800001e+10]
 [-5.2949228e+00]
 [-2.0000002e+08]
 [-2.0000002e+08]
 [-1.1036799e+01]
 [-3.2000003e+09]
 [-3.2000003e+09]
 [-3.2000003e+09]
 [-3.2000003e+09]
 [-3.2000003e+09]
 [-1.2800001e+10]
 [-1.2200555e+01]
 [-1.2800001e+10]
 [-3.2000003e+09]
 [-1.1207850e+01]
 [-3.2000003e+09]
 [-1.1634324e+01]
 [-1.2746425e+01]
 [-5.1200004e+10]
 [-5.1200004e+10]
 [-1.2800001e+10]
 [-1.2800001e+10]
 [-1.1678657e+01]
 [-1.1548667e+01]
 [-1.2360309e+01]
 [-1.2800001e+10]
 [-1.9165890e+01]
 [-1.2800001e+10]
 [-5.1200004e+10]
 [-1.2800001e+10]
 [-1.1707307e+01]
 [-5.1200004e+10]
 [-5.1200004e+10]
 [-1.1817676e+01]
 [-1.1827327e+01]
 [-5.1200004e+10]
 [-1.2800001e+10]
 [-1.2011102e+01]
 [-1.2800001e+10]
 [-1.2800001e+10]
 [-1.3016805e+01]
 [-1.1929576e+01]
 [-1.2800001e+10]
 [-5.1200004e+10]
 [-1.2800001e+10]
 [-1.2103433e+01]
 [-5.12000

[[-1.17497320e+01]
 [-1.13704996e+01]
 [-1.15546446e+01]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-1.15515566e+01]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-1.26890478e+01]
 [-1.20080271e+01]
 [-1.52878790e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.28161612e+01]
 [-5.12000041e+10]
 [-1.42472048e+01]
 [-2.04800016e+11]
 [-5.12000041e+10]
 [-1.22460794e+01]
 [-5.12000041e+10]
 [-1.22743082e+01]
 [-1.33667860e+01]
 [-1.23468504e+01]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.25861330e+01]
 [-5.12000041e+10]
 [-1.36110239e+01]
 [-5.34690094e+00]
 [-9.12024784e+00]
 [-8.00000064e+08]
 [-1.02372580e+01]
 [-9.67215252e+00]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.26304235e+01]
 [-1.06387911e+01]
 [-8.00000064e+08]
 [-1.08505735e+01]
 [-1.09733171e+01]
 [-1.27885847e+01]
 [-3.20000026e+09]
 [-1.16974401e+01]
 [-1.14544439e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.23452272e+01]
 [-1.1785538

[[-1.2410897e+01]
 [-1.2415420e+01]
 [-2.0480002e+11]
 [-2.0480002e+11]
 [-1.9531795e+05]
 [-4.5000006e+08]
 [-1.8000001e+09]
 [-1.0350390e+01]
 [-3.2000003e+09]
 [-3.2000003e+09]
 [-3.2000003e+09]
 [-1.2800001e+10]
 [-3.2000003e+09]
 [-1.1480599e+01]
 [-1.2800001e+10]
 [-1.1191503e+01]
 [-1.2097556e+01]
 [-2.8800002e+10]
 [-3.2000003e+09]
 [-1.2800001e+10]
 [-1.1575225e+01]
 [-1.1873897e+01]
 [-1.2908305e+01]
 [-1.2753694e+01]
 [-1.2800001e+10]
 [-1.2367230e+01]
 [-1.2800001e+10]
 [-1.2356843e+01]
 [-1.1535960e+01]
 [-1.2800001e+10]
 [-1.2139924e+01]
 [-1.2800001e+10]
 [-5.1200004e+10]
 [-1.1952191e+01]
 [-1.2800001e+10]
 [-1.4809709e+01]
 [-5.1200004e+10]
 [-2.0480002e+11]
 [-2.0480002e+11]
 [-1.4669831e+01]
 [-5.1200004e+10]
 [-1.3081321e+01]
 [-5.1200004e+10]
 [-5.1200004e+10]
 [-5.1200004e+10]
 [-5.1200004e+10]
 [-5.1200004e+10]
 [-5.1200004e+10]
 [-5.1200004e+10]
 [-1.3700221e+01]
 [-1.3965034e+01]
 [-2.0480002e+11]
 [-1.3881206e+01]
 [-5.1200004e+10]
 [-6.7771101e+00]
 [-7.81257

[[-1.28000010e+10]
 [-1.25404940e+01]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.22371969e+01]
 [-5.12000041e+10]
 [-1.34719076e+01]
 [-5.12000041e+10]
 [-1.28694658e+01]
 [-5.12000041e+10]
 [-1.21404009e+01]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-1.20099611e+01]
 [-1.31126871e+01]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-2.04800016e+11]
 [-1.22549791e+01]
 [-5.12000041e+10]
 [-1.23716173e+01]
 [-5.50732517e+00]
 [-9.13843822e+00]
 [-8.00000064e+08]
 [-1.07396441e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.18172159e+01]
 [-1.28000010e+10]
 [-1.17342405e+01]
 [-1.21988401e+01]
 [-1.28000010e+10]
 [-1.15200008e+11]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-1.15200008e+11]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.24376345e+01]
 [-1.20944338e+01]
 [-5.12000041e+10]
 [-2.04800016e+11]
 [-1.2257063

[[-8.00000064e+08]
 [-3.20000026e+09]
 [-1.24914122e+01]
 [-3.20000026e+09]
 [-1.13541803e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.35369463e+01]
 [-1.17008085e+01]
 [-5.12000041e+10]
 [-1.17655172e+01]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-1.20599051e+01]
 [-1.20665026e+01]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.23044939e+01]
 [-2.04800016e+11]
 [-1.44199419e+01]
 [-1.21893167e+01]
 [-1.24540205e+01]
 [-2.04800016e+11]
 [-2.04800016e+11]
 [-1.23386869e+01]
 [-1.25633116e+01]
 [-1.30334349e+01]
 [-1.24822626e+01]
 [-1.23931513e+01]
 [-2.04800016e+11]
 [-5.12000041e+10]
 [-1.29956846e+01]
 [-1.54805651e+01]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-2.04800016e+11]
 [-5.12000041e+10]
 [-1.48582525e+01]
 [-5.12000041e+10]
 [-4.60800033e+11]
 [-1.23216143e+01]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-2.04800016e+11]
 [-2.04800016e+11]
 [-4.88337109e+04]
 [-9.99236774e+00]
 [-1.18314142e+01]
 [-9.22642040e+00]
 [-8.0000006

[[-1.17548647e+01]
 [-1.15705442e+01]
 [-5.12000041e+10]
 [-1.26853762e+01]
 [-1.28000010e+10]
 [-1.18731699e+01]
 [-1.20077715e+01]
 [-1.20263472e+01]
 [-2.04800016e+11]
 [-1.44412832e+01]
 [-1.20379267e+01]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-1.20592508e+01]
 [-5.12000041e+10]
 [-1.23299799e+01]
 [-1.26145372e+01]
 [-5.12000041e+10]
 [-4.88345547e+04]
 [-7.26766205e+00]
 [-8.02244091e+00]
 [-1.25000090e+07]
 [-9.11767864e+00]
 [-9.67650318e+00]
 [-1.02382174e+01]
 [-9.51311970e+00]
 [-1.08628206e+01]
 [-1.07875795e+01]
 [-9.94668102e+00]
 [-1.04237165e+01]
 [-1.13553495e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.12435369e+01]
 [-1.34697256e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.17218580e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.11978922e+01]
 [-1.14081640e+01]
 [-1.14874773e+01]
 [-1.28000010e+10]
 [-1.23796835e+01]
 [-1.22384901e+01]
 [-1.28000010e+10]
 [-1.19061384e+01]
 [-1.2800001

[[-8.00000064e+08]
 [-8.00000064e+08]
 [-1.16369734e+01]
 [-1.13632956e+01]
 [-3.20000026e+09]
 [-1.16629000e+01]
 [-1.15101480e+01]
 [-1.33261557e+01]
 [-1.17712030e+01]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.19042616e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.32567606e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-1.33081446e+01]
 [-1.25574694e+01]
 [-1.28000010e+10]
 [-1.20029135e+01]
 [-1.34561281e+01]
 [-1.15200008e+11]
 [-1.27783937e+01]
 [-1.21881571e+01]
 [-1.22312441e+01]
 [-1.24102640e+01]
 [-5.12000041e+10]
 [-1.26659422e+01]
 [-5.12000041e+10]
 [-2.04800016e+11]
 [-1.24514208e+01]
 [-1.26313143e+01]
 [-5.12000041e+10]
 [-1.29910173e+01]
 [-1.36933451e+01]
 [-5.12000041e+10]
 [-2.04800016e+11]
 [-4.88336992e+04]
 [-2.00000016e+08]
 [-2.81250100e+07]
 [-9.34726620e+00]
 [-5.00000120e+07]
 [-5.00000160e+07]
 [-2.00000016e+08]
 [-9.68139744e+00]
 [-9.10074711e+00]
 [-2.00000016e+08]
 [-8.0000006

[[-1.2185367e+01]
 [-2.0480002e+11]
 [-2.0480002e+11]
 [-5.1200004e+10]
 [-1.2256146e+01]
 [-5.1200004e+10]
 [-2.0480002e+11]
 [-5.1200004e+10]
 [-1.2385943e+01]
 [-5.1200004e+10]
 [-2.0480002e+11]
 [-1.2468400e+01]
 [-1.4016376e+01]
 [-1.2437516e+01]
 [-4.8833531e+04]
 [-8.0000006e+08]
 [-8.0000006e+08]
 [-1.0313611e+01]
 [-3.2000003e+09]
 [-3.2000003e+09]
 [-1.2800001e+10]
 [-3.2000003e+09]
 [-1.3891864e+01]
 [-1.2800001e+10]
 [-1.2800001e+10]
 [-1.2395316e+01]
 [-1.2231130e+01]
 [-1.1881059e+01]
 [-1.2013549e+01]
 [-5.1200004e+10]
 [-1.2800001e+10]
 [-1.1741471e+01]
 [-5.1200004e+10]
 [-5.1200004e+10]
 [-5.1200004e+10]
 [-1.1520001e+11]
 [-5.1200004e+10]
 [-1.2832528e+01]
 [-1.2018819e+01]
 [-1.2236581e+01]
 [-2.0480002e+11]
 [-5.1200004e+10]
 [-1.3689979e+01]
 [-5.1200004e+10]
 [-1.2088471e+01]
 [-2.0480002e+11]
 [-1.2329112e+01]
 [-5.1200004e+10]
 [-1.3138064e+01]
 [-1.2666167e+01]
 [-1.2862052e+01]
 [-5.1200004e+10]
 [-1.2800001e+10]
 [-1.2117478e+01]
 [-2.0480002e+11]
 [-5.12000

[[-1.12487593e+01]
 [-1.28000010e+10]
 [-1.21418905e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-5.12000041e+10]
 [-1.17623663e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.42895346e+01]
 [-1.28000010e+10]
 [-1.17535582e+01]
 [-1.22384233e+01]
 [-1.15276232e+01]
 [-1.16259775e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.19486589e+01]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-2.04800016e+11]
 [-1.27948885e+01]
 [-1.24507742e+01]
 [-1.26063375e+01]
 [-5.12000041e+10]
 [-2.04800016e+11]
 [-5.12000041e+10]
 [-2.04800016e+11]
 [-2.04800016e+11]
 [-6.06396389e+00]
 [-7.57113457e+00]
 [-3.12500925e+06]
 [-8.64395428e+00]
 [-9.28625584e+00]
 [-8.94416142e+00]
 [-5.00000120e+07]
 [-2.00000016e+08]
 [-2.00000016e+08]
 [-5.00000160e+07]
 [-5.00000120e+07]
 [-1.11464853e+01]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-1.09102201e+01]
 [-1.28000010e+10]
 [-3.2000002

[[-8.19200066e+11]
 [-1.32739611e+01]
 [-1.44257650e+01]
 [-5.12000041e+10]
 [-8.19200066e+11]
 [-1.28762064e+01]
 [-2.04800016e+11]
 [-5.12000041e+10]
 [-4.88336523e+04]
 [-2.00000016e+08]
 [-9.85323048e+00]
 [-8.00000064e+08]
 [-1.06180735e+01]
 [-1.09141397e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.11900244e+01]
 [-1.15270166e+01]
 [-5.12000041e+10]
 [-1.18170424e+01]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.17553453e+01]
 [-1.25030603e+01]
 [-1.22302427e+01]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.17397184e+01]
 [-1.17907801e+01]
 [-1.59598379e+01]
 [-1.28000010e+10]
 [-1.22348776e+01]
 [-1.28000010e+10]
 [-1.21679106e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.23365850e+01]
 [-2.04800016e+11]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.21657705e+01]
 [-1.25383501e+01]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.2632926

[[-5.12000041e+10]
 [-1.22066717e+01]
 [-1.23401632e+01]
 [-1.22610159e+01]
 [-2.04800016e+11]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.31657057e+01]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-2.04800016e+11]
 [-2.04800016e+11]
 [-1.24498491e+01]
 [-5.12000041e+10]
 [-1.27784414e+01]
 [-5.12000041e+10]
 [-1.31917315e+01]
 [-5.12000041e+10]
 [-2.04800016e+11]
 [-5.12000041e+10]
 [-1.64910469e+01]
 [-2.04800016e+11]
 [-1.26854925e+01]
 [-1.39492025e+01]
 [-2.04800016e+11]
 [-2.04800016e+11]
 [-1.26811495e+01]
 [-1.28596468e+01]
 [-5.34238052e+00]
 [-5.00000120e+07]
 [-9.81022358e+00]
 [-3.20000026e+09]
 [-1.06851721e+01]
 [-1.10663195e+01]
 [-3.20000026e+09]
 [-1.13450212e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.20255041e+01]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-1.15395269e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-1.19307661e+01]
 [-1.22576914e+01]
 [-2.04800016e+11]
 [-1.2528389

[[-5.12000041e+10]
 [-1.24882002e+01]
 [-4.88338242e+04]
 [-7.81257188e+05]
 [-7.81257062e+05]
 [-8.90379429e+00]
 [-2.00000016e+08]
 [-1.25000100e+07]
 [-8.00000064e+08]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-1.08217897e+01]
 [-1.14360571e+01]
 [-1.19089994e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-1.22724714e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-1.45672445e+01]
 [-1.28000010e+10]
 [-1.20540247e+01]
 [-1.19740763e+01]
 [-5.12000041e+10]
 [-1.35114927e+01]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.38019876e+01]
 [-1.28000010e+10]
 [-1.17535448e+01]
 [-1.19184408e+01]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.31635218e+01]
 [-1.25714445e+01]
 [-1.26926584e+01]
 [-2.04800016e+11]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.20823927e+01]
 [-4.8835179

[[-1.29151754e+01]
 [-5.12000041e+10]
 [-1.25766516e+01]
 [-1.25505056e+01]
 [-5.12000041e+10]
 [-1.21557455e+01]
 [-1.23046980e+01]
 [-1.26044283e+01]
 [-1.28000010e+10]
 [-1.21521730e+01]
 [-1.21470366e+01]
 [-2.04800016e+11]
 [-1.21791620e+01]
 [-1.21753397e+01]
 [-1.26531286e+01]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-2.04800016e+11]
 [-2.04800016e+11]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.22692156e+01]
 [-5.12000041e+10]
 [-1.29765081e+01]
 [-5.66536427e+00]
 [-5.00000120e+07]
 [-3.12500900e+06]
 [-3.12501000e+06]
 [-1.25000090e+07]
 [-1.25000090e+07]
 [-8.12633610e+00]
 [-1.25000100e+07]
 [-5.00000120e+07]
 [-3.20000026e+09]
 [-1.06589613e+01]
 [-1.21102514e+01]
 [-2.00000016e+08]
 [-2.00000016e+08]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.04384451e+01]
 [-1.06144762e+01]
 [-1.12828684e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.17597494e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.16818151e+01]
 [-1.28000010e+10]
 [-1.2800001

[[-8.00000064e+08]
 [-9.93802929e+00]
 [-1.03205214e+01]
 [-1.12622118e+01]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.14890280e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.03435831e+01]
 [-1.07507944e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.35087500e+01]
 [-1.28000010e+10]
 [-1.12257166e+01]
 [-1.40525084e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.19923735e+01]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-1.27512064e+01]
 [-1.22846842e+01]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.16886511e+01]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.14879408e+01]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.25354471e+01]
 [-1.28000010e+10]
 [-1.15200008e+11]
 [-1.22090120e+01]
 [-1.28000010e+10]
 [-1.18847799e+01]
 [-1.13769655e+01]
 [-4.88336172e+04]
 [-5.00000120e+07]
 [-2.00000016e+08]
 [-3.20000026e+09]
 [-2.00000016e+08]
 [-8.13033962e+00]
 [-9.8554029

[[-1.28000010e+10]
 [-5.12000041e+10]
 [-1.30190248e+01]
 [-1.26918173e+01]
 [-1.28000010e+10]
 [-1.26498919e+01]
 [-5.12000041e+10]
 [-1.20439043e+01]
 [-1.21206656e+01]
 [-1.22285395e+01]
 [-1.23226271e+01]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.22439451e+01]
 [-5.12000041e+10]
 [-1.30647573e+01]
 [-5.12000041e+10]
 [-1.33768187e+01]
 [-5.47911835e+00]
 [-7.03125800e+06]
 [-7.81256875e+05]
 [-8.42310238e+00]
 [-3.12500800e+06]
 [-1.25000090e+07]
 [-1.05423651e+01]
 [-5.00000120e+07]
 [-8.63658810e+00]
 [-2.00000016e+08]
 [-3.20000026e+09]
 [-1.26686468e+01]
 [-1.18975325e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.16772261e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.18159971e+01]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-1.20349112e+01]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-1.19178057e+01]
 [-5.12000041e+10]
 [-1.2608183

[[-1.28000010e+10]
 [-1.32158327e+01]
 [-1.28000010e+10]
 [-1.19385061e+01]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.22515917e+01]
 [-1.25248976e+01]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.43451586e+01]
 [-5.12000041e+10]
 [-1.22627249e+01]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.24362020e+01]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-2.04800016e+11]
 [-1.20666952e+01]
 [-1.21832514e+01]
 [-5.12000041e+10]
 [-1.23642530e+01]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.24885759e+01]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-1.24451818e+01]
 [-2.04800016e+11]
 [-1.27567225e+01]
 [-5.12000041e+10]
 [-1.28275118e+01]
 [-1.26914682e+01]
 [-2.04800016e+11]
 [-1.30344076e+01]
 [-5.33221817e+00]
 [-9.20905399e+00]
 [-2.00000016e+08]
 [-1.05262270e+01]
 [-9.20824718e+00]
 [-8.00000064e+08]
 [-3.20000026e+09]
 [-1.07557344e+01]
 [-1.08792791e+01]
 [-1.19886637e+01]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.2800001

[[-1.24986620e+01]
 [-2.04800016e+11]
 [-2.04800016e+11]
 [-2.04800016e+11]
 [-5.12000041e+10]
 [-1.27779570e+01]
 [-2.04800016e+11]
 [-1.36112146e+01]
 [-5.12000041e+10]
 [-5.12000041e+10]
 [-2.04800016e+11]
 [-1.27150087e+01]
 [-4.88338945e+04]
 [-7.81258000e+05]
 [-7.81256500e+05]
 [-7.81362057e+00]
 [-5.00000160e+07]
 [-3.12500800e+06]
 [-8.89557362e+00]
 [-1.23544607e+01]
 [-8.01467991e+00]
 [-1.25000090e+07]
 [-3.20000026e+09]
 [-1.08248205e+01]
 [-1.15131254e+01]
 [-1.17392168e+01]
 [-1.09236383e+01]
 [-1.21774302e+01]
 [-1.08928270e+01]
 [-1.39988585e+01]
 [-1.18608103e+01]
 [-1.11282988e+01]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-1.28000010e+10]
 [-1.26525946e+01]
 [-5.12000041e+10]
 [-3.20000026e+09]
 [-1.28000010e+10]
 [-3.20000026e+09]
 [-1.17052164e+01]
 [-1.14997263e+01]
 [-1.28000010e+10]
 [-1.29045286e+01]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-1.19429388e+01]
 [-5.12000041e+10]
 [-1.28000010e+10]
 [-5.12000041e+10]
 [-1.21228838e+01]
 [-5.12000041e+10]
 [-5.1200004

AssertionError: 

In [ ]:
evaluate(env, agent, eval_cfg)